apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: dev
data:
  APP_ENV: development
  LOG_LEVEL: info
  DB_HOST: mysql
  DB_NAME: appdb
  DB_PORT: "5432"
  CACHE_HOST: redis
  CACHE_PORT: "6379"
  REDIS_HOST: redis
